### model
model_name_or_path: ../models/Qwen2.5-7B-Instruct
trust_remote_code: true
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all

### dataset
dataset: Glaive-Code-Assistant-V2 # video: mllm_video_demo
template: qwen
cutoff_len: 8192
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ../data/coding7B/Glaive-Code-Assistant-V2
logging_steps: 10
save_steps: 1
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 13.14
lr_scheduler_type: cosine
warmup_ratio: 0.01
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: saves/coding7B/Glaive-Code-Assistant-V2/checkpoint-4000
### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
